---
# download data from Divvy
creates: data/Divvy_Stations_Trips_2013.zip
command: 
   - mkdir -p $(dirname {{creates}})
   - curl http://divvybikes.com/assets/images/Divvy_Stations_Trips_2013.zip > {{creates}}
---
creates: data/Divvy_Stations_Trips_2013/
depends: data/Divvy_Stations_Trips_2013.zip
command: 
   - unzip {{depends}} -d $(dirname {{depends}})
---
creates: web/data/Station_Data.csv
depends: 
   - data/Divvy_Stations_Trips_2013/
   - munge/aggregate_trips.py
command: 
   - mkdir -p $(dirname {{creates}})
   - python {{depends[1]}}
---
creates: web/server_is_up
depends: web/data/Station_Data.csv
command:
   - touch {{creates}}
   - cd $(dirname {{creates}}) && python -m SimpleHTTPServer
